### PR TITLE
Samplesheet multilevel nesting ick4

### PR DESCRIPTION
**Pull request by jessicarowell**
This branch adds an option to choose which files to create the samplesheet (and thus, run the pipeline) on.  It defaults to only running the pipeline on fastq files nested in subdirectories, the default CDC Core format.  But you can instead choose to run the pipeline on all the files (top-nested and one-dir-under nested) or only the top-level files. 

Test cmd:
`nextflow run main.nf --indir /scicomp/groups-pure/Projects/scbs_mpob/JRowell_ick4/mpox_testing/paired/ --file_levels <nested, all, top> --outdir /scicomp/groups-pure/Projects/scbs_mpob/JRowell_ick4/mpox_testing/results/ --project_name test -config /scicomp/reference/nextflow/configs/cdc-dev.config -profile singularity,rosalind`

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mpxvassembly/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/mpxvassembly _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by mikeyweigand** [comment]
Please remove option `--file_levels all` because it utilizes inconsistent sample name derivation and reinforces poor data organization practices. Users should have option to define:
`top` -- look for fastq files in listed directory only
`nested` -- look for fastq files organized in subdirs one level down

in either scenario, ignore any other fastq files present in the directory tree passed to `--indir`.

**Comment by jessicarowell** [comment]
I have removed the `--file_levels all` option and updated the documentation to reflect this.

**Comment by mikeyweigand** [comment]
This needs some param validation because running with `--file_levels all` attempts to execute but returns warning:

NOTE: Process `POLKAPOX_ASSEMBLY:POLKAPOX:CREATE_SAMPLESHEET` terminated with an error exit status (2) -- Error is ignored

**Comment by jessicarowell** [comment]
I've enforced the valid values for `--file_levels` in nextflow

**Review by mikeyweigand — APPROVED** [review]
Looks good.

**Pull request merged**
